name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.VUEPRESS_BLOG_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          node-version: ${{ matrix.node-version }}
